version: "1"
tls:
  enabled: false
applications:
  - trigger:
      type: "http"
      name: "" #component name
      metadata:
      - name: "path"
        value: "/service-call/*"
    source:
      type: "file"
      path: "examples/service-call/main.wasm"
    enabled-components:
    - "statestore"
components:

